= Notes on dotfiles in general and Omarchy-specific tweaks
:toc:
:toclevels: 4
:toc: preamble
:icons: font

My notes on dotfiles in general and tweaks specific to https://omarchy.org/[Omarchy].

== dotfiles

=== Motivation

Around year 2000, I heard, saw, and - I vaguely recall - used myself
a bare repository approach to store my configuration files.
Since I change my desktop computer only every 6-7 years on the average,
it did not make sense to formalize it.

Now that I use https://dub.podval.org/notes/SystemAdministration/Omarchy.html[Omarchy]
on both my https://dub.podval.org/notes/SystemAdministration/Desktop/Framework%20Laptop%2013.html[Framework laptop]
and https://dub.podval.org/notes/SystemAdministration/Desktop/Desktop%202024.html[Desktop 2024],
maybe it is time to try again ;)

=== Approach

The options I see are:

- https://www.gnu.org/software/stow/[GNU stow]:
although recommended in the Omarchy Manual,
its symlink-based approach does not appeal to me;
- bare GIT repository:
there are many https://www.atlassian.com/git/tutorials/dotfiles[guides],
but I'd like something that helps with creating and maintaining the dotfiles repository;
- https://yadm.io/[yadm] seems to be a thin enough wrapper around a GIT repository
which does help with routine tasks;
- https://www.chezmoi.io/[chezmoi] gets a lot of praise for better templating than `yadm`,
but since I don't even understand what templating is, let alone need it,
I am going to go with `yadm` for now :)

`yadm` arranges for the home directory to be the work tree of the dotfiles repository
which it stores in `~/.local/share/yadm/repo.git`.

== yadm

=== Installation

To install `yadm` on `Omarchy`:

[source,shell]
----
$ sudo pacman -S yadm
----

=== bootstrap

After checkout, `yadm` https://yadm.io/docs/bootstrap[runs]
`~/.config/yadm/bootstrap` executable;
it can also be run explicitly: `yadm bootstrap`.
I use a https://github.com/dubinsky/dotfiles/tree/master/.config/yadm/bootstrap[script] copied from the `yadm` manual
which runs all the executables in `~/.config/yadm/bootstrap.d/`.

=== README

There are https://github.com/yadm-dev/yadm/issues/93[ways] to add README
to the `yadm` repository without polluting the home directory;
I do not want to deal with `sparse checkout`, so I just put `README.adoc` under `.github` ;)

=== Secrets

If I decide to store secrets in my `dotfiles` repository
(Cloudflare API tokens, Google Cloud Platform keys etc.),
`yadm` provides https://yadm.io/docs/encryption#[its own way]
of doing that, but there are approaches that are not `yadm`-specific:

- https://github.com/AGWA/git-crypt[git-crypt]
- https://github.com/elasticdog/transcrypt[transcrypt]
- https://github.com/sobolevn/git-secret[git-secret]
- https://github.com/getsops/sops[SOPS]

`yadm` supports `transcrypt`  and `git-crypt` directly.

== Omarchy

=== Bootstrap

I use `yadm bootstrap` to install things that I need:

- https://github.com/dubinsky/dotfiles/tree/master/.config/yadm/bootstrap.d/aur-packages.txt[AUR]
https://github.com/dubinsky/dotfiles/tree/master/.config/yadm/bootstrap.d/install-aur-packages.sh[packages];

- https://github.com/dubinsky/dotfiles/tree/master/.config/yadm/bootstrap.d/java.sh[Java];

- https://github.com/dubinsky/dotfiles/tree/master/.config/yadm/bootstrap.d/yubikey.sh[Yubikey];

- https://github.com/dubinsky/dotfiles/tree/master/.config/yadm/bootstrap.d/pulumi.sh[Pulumi and Besom];

- https://github.com/dubinsky/dotfiles/tree/master/.config/yadm/bootstrap.d/asciidoctor.sh[Asciidoctor];

- https://github.com/dubinsky/dotfiles/tree/master/.config/yadm/bootstrap.d/bitwarden.sh[Bitwarden to replace 1Password];

- https://github.com/dubinsky/dotfiles/tree/master/.config/yadm/bootstrap.d/keyboards.sh[ZSA keyboards];

=== Network
By default, `Omarchy` uses DNS servers provided by DHCP; if not:
`Omarchy | Setup | DNS`: use DHCP.

IMPORTANT: By default, search domain provided by DHCP is *not* used;
to configure it, in `/etc/systemd/network/20-ethernet.network` and `/etc/systemd/network/20-wlan.network` add:

[source]
----
[Network]
UseDomains=yes
----

=== Configuration

- `direnv` hooked into the shell:
https://github.com/dubinsky/dotfiles/tree/master/.bashrc[~/.bashrc];

- `direnv` status in the prompt: https://github.com/dubinsky/dotfiles/tree/master/.config/starship.toml[~/.config/starship.toml];

- `SSH` agent socket: https://github.com/dubinsky/dotfiles/tree/master/.config/uwsm/env[~/.config/uwsm/env];

- `keymapp` on the path: https://github.com/dubinsky/dotfiles/tree/master/.bash_profile[~/.bash_profile];

- `Bitwarden` keyboard binding (replaces `1Password`):
https://github.com/dubinsky/dotfiles/tree/master/.config/hypr/bindings.conf[~/.config/hypr/bindings.conf];

- `IntelliJ` keyboard binding:
https://github.com/dubinsky/dotfiles/tree/master/.config/hypr/bindings.conf[~/.config/hypr/bindings.conf];

=== Chromium

To be able to log into Google account and synchronize bookmarks etc., run:
`Omarchy | Install | Service | Chromium Account`

TODO what theme should I use to be able to change font size?

=== Monitors


=== ZSA Moonlander Keyboard

TODO add desktop entry and/or key binding for keymapp...

=== Fonts

There is a TUI for changing the terminal font, but not for changing font size.

Terminal font for `Ghosttty`:  `~/.config/ghosttty/config`.

Terminal font for  `Alacritty`: `~/.config/alacritty/alacritty.toml`.

Top bar (`Waybar`) font: `~/.config/waybar/style.css`.

Obsidian: there does not seem any way to configure the font!


=== Obsidian
Enable community plugins.

For Obsidian to follow theme changes, its theme needs to be manually set to `Omarchy`; this theme becomes available in an Obsidian vault only after Omarchy theme was changed at least once after Obsidian vault was opened.

To increase font size of both the user interface that the editor, I set `Settings | Appearance | Advanced | Zoom level` to 150%a and `Settings | Appearance | Font size` to 16.

=== Keyboard Layouts
https://learn.omacom.io/2/the-omarchy-manual/78/keyboard-mouse-trackpad[Omarchy Manual] explains that keyboard layout can be added in `~/.config/hypr/input.conf`:

[source]
----
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  kb_layout = us,ru(phonetic)
  kb_options = compose:caps,grp:alts_toggle
----

To list available keyboard layouts:

[source,shell]
----
$ localectl list-keymaps
----

The list of available toggles:

[source,shell]
----
$ grep -hroE 'grp:.*toggle ' /usr/share/X11/xkb/rules/ | sort -u
----
Omarchy Manual also https://learn.omacom.io/2/the-omarchy-manual/67/faq[points]
to https://github.com/basecamp/omarchy/discussions/111[instructions]
on how to add layout indicator and selector to the top bar
in `~/.config/waybar/config.jsonc`:

[source,json]
----
"modules-right": [
  "hyprland/language",
],
"hyprland/language": {
  "format": "{}",
  "format-en": "US",
  "format-ru": "RU",
  "on-click": "hyprctl switchxkblayout <keyboard-device-name> next"
}
----

Keyboard device name can be determined by:

[source,shell]
----
$ hyprctl devices
----

`<keyboard-device-name>` can also be `current` or `all`.

Styling of the above is configured in
`~/.config/waybar/style.css`:

[source,css]
----
#language {
  min-width: 12px;
  margin: 0 7.5px;
}
----

To restart Waybar:

[source,shell]
----
$ pkill waybar && hyprctl dispatch exec waybar
----

=== JetBrains

JetBrains IDEs now support Wayland natively, but it is not enabled by default; to https://youtrack.jetbrains.com/articles/SUPPORT-A-1166/Linux-how-to-turn-on-off-native-Wayland-mode[turn it on]:
select `Help | Edit custom VM options` and add `-Dawt.toolkit.name=WLToolkit`.


`~/.config/hypr/jetbrains.conf`


`~/.config/hypr/hyprland.conf`: include `~/.config/hypr/jetbrains.conf`
