= Notes on dotfiles in general and Omarchy-specific tweaks
:toc:
:toclevels: 4
:toc: preamble
:icons: font

My notes on dotfiles in general and tweaks specific to https://omarchy.org/[Omarchy].

== dotfiles

=== Motivation

Around year 2000, I heard, saw, and - I vaguely recall - used myself
a bare repository approach to store my configuration files.
Since I change my desktop computer only every 6-7 years on the average,
it did not make sense to formalize it.

Now that I use https://dub.podval.org/notes/SystemAdministration/Omarchy.html[Omarchy]
on both my https://dub.podval.org/notes/SystemAdministration/Desktop/Framework%20Laptop%2013.html[Framework laptop]
and https://dub.podval.org/notes/SystemAdministration/Desktop/Desktop%202024.html[Desktop 2024],
maybe it is time to try again ;)

=== Approach

The options I see are:

- https://www.gnu.org/software/stow/[GNU stow]:
although recommended in the Omarchy Manual,
its symlink-based approach does not appeal to me;
- bare GIT repository:
there are many https://www.atlassian.com/git/tutorials/dotfiles[guides],
but I'd like something that helps with creating and maintaining the dotfiles repository;
- https://yadm.io/[yadm] seems to be a thin enough wrapper around a GIT repository
which does help with routine tasks;
- https://www.chezmoi.io/[chezmoi] gets a lot of praise for better templating than `yadm`,
but since I don't even understand what templating is, let alone need it,
I am going to go with `yadm` for now :)

`yadm` arranges for the home directory to be the work tree of the dotfiles repository
which it stores in `.local/share/yadm/repo.git`.

== yadm

=== Installation

To install `yadm` on `Omarchy`:

[source,shell]
----
$ sudo pacman -S yadm
$ yadm init
$ yadm remote add origin "git@github.com:dubinsky/dotfiles.git"
$ yadm add <file>
$ yadm commit -m "<message>"
$ yadm push
----

=== Bootstrap

After checkout, `yadm` https://yadm.io/docs/bootstrap[runs]
`.config/yadm/bootstrap` executable;
it can also be run explicitly: `yadm bootstrap`.
I use a https://github.com/dubinsky/dotfiles/tree/master/.config/yadm/bootstrap[script] copied from the `yadm` manual
which runs all the executables in `.config/yadm/bootstrap.d/`.

=== Readme

There are https://github.com/yadm-dev/yadm/issues/93[ways] to add README
to the `yadm` repository without polluting the home directory;
I do not want to deal with `sparse checkout`, so I just put `README.adoc` under `.github` ;)

=== Secrets

If I decide to store secrets in my `dotfiles` repository
(Cloudflare API tokens, Google Cloud Platform keys etc.),
`yadm` provides https://yadm.io/docs/encryption#[its own way]
of doing that, but there are approaches that are not `yadm`-specific:

- https://github.com/AGWA/git-crypt[git-crypt]
- https://github.com/elasticdog/transcrypt[transcrypt]
- https://github.com/sobolevn/git-secret[git-secret]
- https://github.com/getsops/sops[SOPS]

`yadm` supports `transcrypt`  and `git-crypt` directly.

=== Clone

On the new machine, run:

[source,shell]
----
$ yadm clone --bootstrap https://github.com/dubinsky/dotfiles.git
----

yadm does not change pre-existing files;
they can be overwritten by `$ yadm checkout <file>`.

== Manual Tweaks

=== Keyboards
- TODO add desktop entry and/or key binding for keymapp...

=== IntelliJ IDEA
- enable native Wayland support:
select `Help | Edit custom VM options` and add `-Dawt.toolkit.name=WLToolkit`;
see  https://youtrack.jetbrains.com/articles/SUPPORT-A-1166/Linux-how-to-turn-on-off-native-Wayland-mode

=== Chromium

- TODO what theme should I use to be able to change font size?

=== Obsidian

- open the vault in `Podval/dub.podval.org`
- change Omarchy theme (this makes Omarchy theme available in Obsidian)
- set theme to `Omarchy` so that Obsidian follows theme changes
- enable community plugins
- to increase font size of both the user interface that the editor, set
`Settings | Appearance | Advanced | Zoom level` to 150% and
`Settings | Appearance | Font size` to 16.

=== Zotero
- install https://github.com/wileyyugioh/zotmoov[ZotMoove] plugin
- install https://retorque.re/zotero-better-bibtex/[Better BibTex] plugin
