= Notes on dotfiles in general and Omarchy-specific tweaks
:toc:
:toclevels: 4
:toc: preamble
:icons: font

My notes on dotfiles in general and tweaks specific to https://omarchy.org/[Omarchy].

== dotfiles

=== Motivation

Around year 2000, I heard, saw, and - I vaguely recall - used myself
a bare repository approach to store my configuration files.
Since I change my desktop computer only every 6-7 years on the average,
it did not make sense to formalize it.

Now that I use https://dub.podval.org/notes/SystemAdministration/Omarchy.html[Omarchy]
on both my https://dub.podval.org/notes/SystemAdministration/Desktop/Framework%20Laptop%2013.html[Framework laptop]
and https://dub.podval.org/notes/SystemAdministration/Desktop/Desktop%202024.html[Desktop 2024],
maybe it is time to try again ;)

=== Approach

The options I see are:

- https://www.gnu.org/software/stow/[GNU stow];
although recommended in the Omarchy Manual,
its symlink-based approach does not appeal to me;
- bare GIT repository:
there are many https://www.atlassian.com/git/tutorials/dotfiles[guides],
but I'd like something that helps with creating and maintaining the dotfiles repository;
- https://yadm.io/[yadm] seems to be a thin enough wrapper around a GIT repository
which does help with routine tasks;
- https://www.chezmoi.io/[chezmoi] gets a lot of praise for better templating than `yadm`,
but since I don't even understand what templating is, let alone need it,
I am going to go with `yadm` for now :)

`yadm` arranges for the home directory to be the work tree of the dotfiles repository
which it stores in `~/.local/share/yadm/repo.git`.

== yadm

=== Installation

To install `yadm` on `Omarchy`:

[source,shell]
----
$ sudo pacman -S yadm
----

=== bootstrap

After checkout, `yadm` https://yadm.io/docs/bootstrap[runs]
`~/.config/yadm/bootstrap` executable;
I use a https://github.com/dubinsky/dotfiles/tree/master/.config/yadm/bootstrap[script] copied from the `yadm` manual
which runs all the executables in `~/.config/yadm/bootstrap.d`.

=== README

There are https://github.com/yadm-dev/yadm/issues/93[ways] to add README
to the `yadm` repository without polluting the home directory;
I do not want to deal with `sparse checkout`, so I just put `README.adoc` under `.github` ;)

=== Secrets

If I decide to store secrets in my `dotfiles` repository
(Cloudflare API tokens, Google Cloud Platform keys etc.),
`yadm` provides https://yadm.io/docs/encryption#[its own way]
of doing that, but there are approaches that are not `yadm`-specific:

- https://github.com/AGWA/git-crypt[git-crypt]
- https://github.com/elasticdog/transcrypt[transcrypt]
- https://github.com/sobolevn/git-secret[git-secret]
- https://github.com/getsops/sops[SOPS]

`yadm` supports `transcrypt`  and `git-crypt` directly.

== Omarchy

=== Packages

I use `yadm bootstrap` to install things that I need:

- https://github.com/dubinsky/dotfiles/tree/master/.config/yadm/bootstrap.d/arch-packages.txt[Arch]
https://github.com/dubinsky/dotfiles/tree/master/.config/yadm/bootstrap.d/install-arch-packages.sh[packages];

- https://github.com/dubinsky/dotfiles/tree/master/.config/yadm/bootstrap.d/aur-packages.txt[AUR]
https://github.com/dubinsky/dotfiles/tree/master/.config/yadm/bootstrap.d/install-aur-packages.sh[packages];

- https://github.com/dubinsky/dotfiles/tree/master/.config/yadm/bootstrap.d/install-java.sh[Java];

- https://github.com/dubinsky/dotfiles/tree/master/.config/yadm/bootstrap.d/install-pulumi.sh[Pulumi and Besom];

- https://github.com/dubinsky/dotfiles/tree/master/.config/yadm/bootstrap.d/install-asciidoctor.sh[Asciidoctor];

- https://github.com/dubinsky/dotfiles/tree/master/.config/yadm/bootstrap.d/install-bitwarden.sh[Bitwarden to replace 1Password];

=== Network
By default, Omarchy uses DNS servers provided by DHCP; if not:
`Omarchy | Setup | DNS`: use DHCP

To use search domain provided by DHCP,
in `/etc/systemd/network/20-ethernet.network` and `/etc/systemd/network/20-wlan.network` add:

[source]
----
[Network]
UseDomains=yes
----

=== Firmware

[source,shell]
----
$ fwupdmgr refresh
$ sudo fwupdmgr update
----

=== DirEnv
To https://direnv.net/docs/hook.html[hook direnv into the shell],
add the following line at the *end* of the `~/.bashrc` file:

[source,shell]
----
eval "$(direnv hook bash)"
----

To add `direnv` status to the prompt, in `~/.config/starship.toml` add:

[source,toml]
----
[direnv]
disabled = false
format = "[$symbol$allowed]($style)"
symbol = "e"
allowed_msg = ""
not_allowed_msg = "✗"
----
and set:

[source,toml]
----
format = "[$directory$git_branch$git_status]($style)$direnv$character"
----

=== Chromium

To be able to log into Google account and synchronize bookmarks etc., run:
`Omarchy | Install | Service | Chromium Account`

TODO what theme should I use to be able to change font size?

=== Yubikey
Enable SSH agent:

[source,shell]
----
$ systemctl enable --now --user ssh-agent.service
----

In `~/.config/uwsm/env`, add:

[source,shell]
----
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
----
Restart the system.

[source,shell]
----
# To add Yubikey credentials to SSH:
$ ssh-add -K
# To list credentials added to the agent:
$ ssh-add -L
----

=== Monitors
Omarchy https://learn.omacom.io/2/the-omarchy-manual/86/monitors[manual]
mentions a TUI utility for setting up monitors - https://github.com/erans/hyprmon/[Hyprmon] - but I found it easy enough to configure monitors by editing `~/.config/hypr/monitors.conf` directly.

In fact, the only lines I have there are:

[source]
----
env = GDK_SCALE,2
monitor=,preferred,auto,auto
----
and everything works fine with both my Framework laptop 13 OLED screen and my 6K Asus monitor :)

To make adjustments independently of the port the monitor is plugged in, use monitor description as a name instead.

To list connected monitors:

[source,shell]
----
$ hyprctl monitors all
----

=== ZSA Moonlander Keyboard
Follow https://github.com/zsa/wally/wiki/Linux-install[Keymapp installation] instructions:

Download https://oryx.nyc3.cdn.digitaloceanspaces.com/keymapp/keymapp-latest.tar.gz[latest Keymapp] and unpack it into `~/.local/share/Keymapp`.

Add to `~/.bash_profile`:

[source,shell]
----
# Keymapp
export PATH="$PATH:/home/dub/.local/share/Keymapp"
----
Log out and back in for the `PATH` to change :)

Create `/etc/udev/rules.d/50-zsa.rules` with:

[source]
----
# Rules for Oryx web flashing and live training
KERNEL=="hidraw*", ATTRS{idVendor}=="16c0", MODE="0664", GROUP="plugdev"
KERNEL=="hidraw*", ATTRS{idVendor}=="3297", MODE="0664", GROUP="plugdev"

# Keymapp / Wally Flashing rules for the Moonlander and Planck EZ
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="df11", MODE:="0666", SYMLINK+="stm32_dfu"
# Keymapp Flashing rules for the Voyager
SUBSYSTEMS=="usb", ATTRS{idVendor}=="3297", MODE:="0666", SYMLINK+="ignition_dfu"
----

Then:

[source,shell]
----
$ sudo groupadd plugdev
$ sudo usermod -aG plugdev $USER
$ sudo udevadm control --reload
$ sudo udevadm trigger
----
Log out and back in for the group to apply :)

TODO add desktop entry and/or key binding for keymapp...

=== Fonts

There is a TUI for changing the terminal font, but not for changing font size.

Terminal font for `Ghosttty` is configured in `~/.config/ghosttty/config`:

[source]
----
# Font
font-family = "JetBrainsMono Nerd Font"
font-style = Regular
font-size = 18
----

Terminal font for  `Alacritty` is configured in  `~/.config/alacritty/alacritty.toml`:

[source,toml]
----
[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 18
----

Top bar (`Waybar`) font is configured in `~/.config/waybar/style.css`:

[source,css]
----
* {
  font-family: 'JetBrainsMono Nerd Font';
  font-size: 20px;
}
----

=== Obsidian
Enable community plugins.

For Obsidian to follow theme changes, its theme needs to be manually set to `Omarchy`; this theme becomes available in an Obsidian vault only after Omarchy theme was changed at least once after Obsidian vault was opened.

To increase font size of both the user interface that the editor, I set `Settings | Appearance | Advanced | Zoom level` to 150%a and `Settings | Appearance | Font size` to 16.

=== Keyboard Layouts
https://learn.omacom.io/2/the-omarchy-manual/78/keyboard-mouse-trackpad[Omarchy Manual] explains that keyboard layout can be added in `~/.config/hypr/input.conf`:

[source]
----
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  kb_layout = us,ru(phonetic)
  kb_options = compose:caps,grp:alts_toggle
----

To list available keyboard layouts:

[source,shell]
----
$ localectl list-keymaps
----

The list of available toggles:

[source,shell]
----
$ grep -hroE 'grp:.*toggle ' /usr/share/X11/xkb/rules/ | sort -u
----
Omarchy Manual also https://learn.omacom.io/2/the-omarchy-manual/67/faq[points]
to https://github.com/basecamp/omarchy/discussions/111[instructions]
on how to add layout indicator and selector to the top bar
in `~/.config/waybar/config.jsonc`:

[source,json]
----
"modules-right": [
  "hyprland/language",
],
"hyprland/language": {
  "format": "{}",
  "format-en": "US",
  "format-ru": "RU",
  "on-click": "hyprctl switchxkblayout <keyboard-device-name> next"
}
----

Keyboard device name can be determined by:

[source,shell]
----
$ hyprctl devices
----

`<keyboard-device-name>` can also be `current` or `all`.

Styling of the above is configured in
`~/.config/waybar/style.css`:

[source,css]
----
#language {
  min-width: 12px;
  margin: 0 7.5px;
}
----

To restart Waybar:

[source,shell]
----
$ pkill waybar && hyprctl dispatch exec waybar
----

=== JetBrains
JetBrains IDEs are available from AUR, but the best way to install and update them is via JetBrains Toolbox, which is also available from AUR :)

JetBrains IDEs now support Wayland natively, but it is not enabled by default; to https://youtrack.jetbrains.com/articles/SUPPORT-A-1166/Linux-how-to-turn-on-off-native-Wayland-mode[turn it on]:
select `Help | Edit custom VM options` and add `-Dawt.toolkit.name=WLToolkit`.

I added a keyboard binding for the IDE in `~/.config/hypr/bindings.conf`:

[source]
----
bindd = SUPER SHIFT, J, IntelliJ Idea, exec, omarchy-launch-or-focus "^idea$" idea
----

When JetBrains IDEs are running on Wayland, their pop-ups are do not get focused, so pop-up where the IDE asks if you trust a project you are trying to open for a first time is not visible and there is no way to say "yes" (or even see the pop-up window) :(

To fix this, windows rules https://github.com/basecamp/omarchy/discussions/100[need] to be https://notes.dsebastien.net/30+Areas/33+Permanent+notes/33.02+Content/How+to+install+IntelliJ+IDEA+on+Omarchy[added].

Create `~/.config/hypr/jetbrains.conf` with:

[source]
----
# Fix all dialogs in Jetbrains products
windowrulev2 = tag +jb, class:^jetbrains-.+$,floating:1
windowrulev2 = stayfocused, tag:jb
windowrulev2 = noinitialfocus, tag:jb
windowrulev2 = focusonactivate,class:^jetbrains-(?!toolbox)

# center the pops excepting context menu
windowrulev2 = move 30% 30%,class:^jetbrains-(?!toolbox),title:^(?!win.*),floating:1
windowrulev2 = size 40% 40%,class:^jetbrains-(?!toolbox),title:^(?!win.*),floating:1

# Fix tooltips (always have a title of `win.<id>`)
# Fix for sidebar menus being unclickable
windowrulev2 = noinitialfocus, class:^(.*jetbrains.*)$, title:^(win.*)$
windowrulev2 = nofocus, class:^(.*jetbrains.*)$, title:^(win.*)$
# Fix tab dragging (always have a single space character as their title)
windowrulev2 = noinitialfocus, class:^(.*jetbrains.*)$, title:^\\s$
windowrulev2 = nofocus, class:^(.*jetbrains.*)$, title:^\\s$
# Additional fixes for tab dragging
windowrulev2 = tag +jb, class:^jetbrains-.+$,floating:1
windowrulev2 = stayfocused, tag:jb
windowrulev2 = noinitialfocus, tag:jb
----

In `~/.config/hypr/hyprland.conf`, add:

[source]
----
# JetBrains IDEs
source = ~/.config/hypr/jetbrains.conf
----

Note: since Omarchy itself ships some windows rules in `~.local/share/omarchy/default/hypr/apps/jetbrains.conf`, it is not clear which (if any) of the above rules are actually needed, nor if the Omarchy-supplied rules need to be disabled...

=== Bitwarden

Change keyboard binding from `1Password` to `Bitwarden` in
`~/.config/hypr/bindings.conf`:

[source,properties]
----
# from:
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password
# to:
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- bitwarden-desktop
----

TODO there does not seem any way to configure the font!
