// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.backgroundErrors", 13);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1767413597);
user_pref("app.update.lastUpdateTime.background-update-timer", 1767456797);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1767413597);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1762235609);
user_pref("browser.laterrun.bookkeeping.sessionCount", 14);
user_pref("browser.startup.homepage_override.buildID", "20240801134912");
user_pref("browser.startup.homepage_override.mstone", "115.14.0");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.lastAppBuildId", "20251221205913");
user_pref("extensions.lastAppVersion", "7.0.30.SOURCE.e9281c51f");
user_pref("extensions.lastPlatformVersion", "115.14.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webextensions.uuids", "{\"zotmoov@wileyy.com\":\"0f147c81-6bee-44fe-b3ce-c4a26ec36b90\",\"better-bibtex@iris-advies.com\":\"47e39f48-6735-45c3-98a5-75996640eb04\"}");
user_pref("extensions.zotero.dataDir", "/home/dub/Books/Zotero");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.lastSelectedPrefPane", "zotmoov_basic");
user_pref("extensions.zotero.lastViewedFolder", "C2");
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"true\"},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-splitter\":{\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"width\":\"337\",\"height\":\"205\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-splitter-stacked\":{\"state\":\"collapsed\"}}");
user_pref("extensions.zotero.panes.abstract.open", true);
user_pref("extensions.zotero.panes.attachment-annotations.open", true);
user_pref("extensions.zotero.panes.attachment-info.open", true);
user_pref("extensions.zotero.panes.attachments.open", true);
user_pref("extensions.zotero.panes.context-all-notes.open", true);
user_pref("extensions.zotero.panes.context-item-notes.open", true);
user_pref("extensions.zotero.panes.info.open", true);
user_pref("extensions.zotero.panes.libraries-collections.open", true);
user_pref("extensions.zotero.panes.notes.open", true);
user_pref("extensions.zotero.panes.related.open", true);
user_pref("extensions.zotero.panes.tags.open", true);
user_pref("extensions.zotero.prefVersion", 13);
user_pref("extensions.zotero.purge.creators", true);
user_pref("extensions.zotero.purge.items", true);
user_pref("extensions.zotero.purge.tags", true);
user_pref("extensions.zotero.sourceList.persist", "{\"L1\":true,\"C14\":true,\"P1\":false}");
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormat", "auth.lower + shorttitle(3, 3) + year");
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormatEditing", "auth.lower + shorttitle(3, 3) + year");
user_pref("extensions.zotero.translators.better-bibtex.path.git", "/usr/bin/git");
user_pref("extensions.zotero.translators.better-bibtex.path.texstudio", "");
user_pref("extensions.zotero.translators.better-bibtex.platform", "lin");
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zoteroOpenOfficeIntegration.lastAttemptedVersion", "7.0.5.SOURCE");
user_pref("extensions.zoteroOpenOfficeIntegration.unopkgPaths", "{\"/usr/bin/unopkg\":true,\"/usr/lib/libreoffice/program/unopkg\":true,\"/usr/lib64/libreoffice/program/unopkg\":true}");
user_pref("extensions.zoteroOpenOfficeIntegration.version", "7.0.5.SOURCE");
user_pref("extensions.zotmoov.dst_dir", "/home/dub/Books/ZoteroAttachments");
user_pref("extensions.zotmoov.enable_automove", false);
user_pref("extensions.zotmoov.enable_subdir_move", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1767413769);
user_pref("intl.accept_languages", "en-US, en");
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1767413769529");
user_pref("security.sandbox.content.tempDirSuffix", "99a96b0e-901f-4878-94fc-ff2ad96dee7e");
user_pref("storage.vacuum.last.content-prefs.sqlite", 1767154569);
user_pref("storage.vacuum.last.index", 2);
user_pref("storage.vacuum.last.places.sqlite", 1767068169);
user_pref("toolkit.startup.last_success", 1763941597);
